### ISSUE TITLE
Revise top link menu

### ISSUE THREAD

**Issue by haydanu** [team-d-impact-byte-batch-haku/weekend-team-project#2]
Add this to css

```css
.navigation-menu a {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    text-decoration: none;
    color: black;
}
```

Inside code below

https://github.com/team-d-impact-byte-batch-haku/Pet-Food/blob/b474a77b4b3e60310eaf5327b18b56849963f653/index.css#L21-L23

Add this

`width: 520px`
