### ISSUE TITLE
Revise footer CSS

### ISSUE THREAD

**Issue by haydanu** [team-d-impact-byte-batch-haku/weekend-team-project#4]
change below code 
https://github.com/team-d-impact-byte-batch-haku/Pet-Food/blob/b474a77b4b3e60310eaf5327b18b56849963f653/index.css#L120-L124

to this: 

```css
.footer {
  display: flex;
  background-color: #3a3a3a;
  color: white;
  justify-content: space-around;
  padding-top: 20px;
}
```

and add this to change color list link item in footer

```css
ul li a {
  text-decoration: none;
  color: white;
}
```

https://github.com/team-d-impact-byte-batch-haku/Pet-Food/blob/b474a77b4b3e60310eaf5327b18b56849963f653/index.css#L136

change margin left to `40px`

`margin-left: 40px;`
